import { Container, Grid } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "../components/Button/Button";
import NavBar from "../components/NavBar/NavBar";
import { Typography } from "../components/Typography/Typography";
import { Card } from "../components/Card/Card";
import { imageIds } from "../data/imageIds";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>MatchGallery | Find your match</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        {/* Todo: Need to look into this warning, Im not familiar with this for next.js */}
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;800&family=Roboto:wght@400;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <NavBar />
      <Container sx={{ marginBottom: 5 }}>
        <Typography
          variant="body1"
          sx={{
            backgroundColor: "gray",
            color: "white",
            padding: 1,
            marginTop: 3,
          }}
        >
          Typography
        </Typography>
        <Typography variant="h1">Test h1... </Typography>
        <Typography variant="subtitle1">Test h2... </Typography>
        <Typography variant="subtitle1">Test subtitle... </Typography>
        <Typography variant="body1">Test body... </Typography>
      </Container>

      <Container sx={{ marginBottom: 5 }}>
        <Typography
          variant="body1"
          sx={{
            backgroundColor: "gray",
            color: "white",
            padding: 1,
            marginTop: 3,
            marginBottom: 3,
          }}
        >
          Buttons
        </Typography>
        <Button>Test Button</Button>
        <Button color="secondary">Test Button</Button>
        <Button color="success">Test Button</Button>
        <Button color="error">Test Button</Button>
        <Button color="info">Test Button</Button>
        <hr />
        <Button variant="outlined">Test Button</Button>
        <Button variant="outlined" color="secondary">
          Test Button
        </Button>
        <Button variant="outlined" color="success">
          Test Button
        </Button>
        <Button variant="outlined" color="error">
          Test Button
        </Button>
        <Button variant="outlined" color="info">
          Test Button
        </Button>
        <hr />
        <Button variant="contained">Test Button</Button>
        <Button variant="contained" color="secondary">
          Test Button
        </Button>
        <Button variant="contained" color="success">
          Test Button
        </Button>
        <Button variant="contained" color="error">
          Test Button
        </Button>
        <Button variant="contained" color="info">
          Test Button
        </Button>
      </Container>

      <Container sx={{ marginBottom: 5 }}>
        <Typography
          variant="body1"
          sx={{
            backgroundColor: "gray",
            color: "white",
            padding: 1,
            marginTop: 3,
            marginBottom: 3,
          }}
        >
          Cards
        </Typography>
        <Grid container justifyContent="center" spacing="20">
          {imageIds.map((imageId) => (
            <Grid key={imageId} item>
              <Card imageId={imageId} />
            </Grid>
          ))}
        </Grid>
      </Container>

      <main></main>

      <footer></footer>
    </div>
  );
};

export default Home;
